language: python

matrix:
  include:
    - os: linux
      python:
        "3.7"
            
      install: 
        - python3 -m pip install zencad

      script:
        - cd utest
        - python3 ./api.py