language: python

matrix:
  include:
    # Self Making with Display (Bionic)
    - name: "Ubuntu: Build(servoce==master)"
      os: linux
      dist: bionic
      if: branch = master
      python:
        - "3.7"

      services:
        - xvfb

      install: 
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        #- sudo add-apt-repository ppa:freecad-maintainers/occt-releases -y
        #- sudo add-apt-repository ppa:freecad-maintainers/freecad-stable -y
        - sudo apt-get update
        #- sudo apt install -y libocct-foundation-7.3 libocct-ocaf-7.3 libocct-data-exchange-7.3 libocct-foundation-dev libocct-ocaf-dev libocct-data-exchange-dev
        
        - python3 -m pip install pyservoce
        - python3 -m pip install evalcache numpy pillow pyopengl PyQt5 psutil
        - python3 -m pip install scikit-image

        - python3 ./setup.py install

      script:
        - cd utest
        - python3 ./api.py
        - python3 ./examples.py

    - name: "Ubuntu: Build(servoce==dev)"
      os: linux
      dist: bionic
      python:
        - "3.7"

      services:
        - xvfb

      install: 
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install libx11-dev mesa-common-dev libglu1-mesa-dev

        - sudo python3 -m pip install requests psutil
        - python3 -m pip install licant wheel requests psutil
        - python3 -m pip install evalcache numpy pillow pyopengl PyQt5 psutil
        - python3 -m pip install scikit-image
        
        - python3 ./setup.py install
        - sudo python3 -m zencad --install-occt-force
        - python3 -m zencad --install-pythonocc-force

      script:
        - cd utest
        - python3 ./api.py
        - python3 ./examples.py

     # Self Making with Display (Bionic)    PyPi
    - name: "Ubuntu: Loading from pypi"
      if: branch = master
      os: linux
      dist: bionic
      python:
        - "3.7"
            
      services:
        - xvfb

      install: 
        - python3 -m pip install zencad

      script:
        - cd utest
        - python3 ./api.py
        - python3 ./examples.py

    - name: "OSX: Loading from pypi"
      if: branch = master
      os: osx
      osx_image: xcode11.2
      language: shell
            
      install: 
        - python3 -m pip install zencad

      script:
        - cd utest
        - python3 ./api.py
        - python3 ./examples.py
