language: python

matrix:
  include:
    - name: "Ubuntu"
      os: linux
      dist: bionic
      python:
        - "3.7"

      services:
        - xvfb

      install: 
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install libx11-dev mesa-common-dev libglu1-mesa-dev

        - python3 -m pip install licant wheel requests psutil
        - python3 -m pip install evalcache numpy pillow pyopengl PyQt5 psutil
        - python3 -m pip install scikit-image zenframe
        
        - python3 ./setup.py install
        - python3 -m zencad --install-pythonocc-force
        - python3 -m zencad --install-occt-to-pythonocc-dir

      script:
        - cd utest
        - python3 ./api.py
        - python3 ./examples.py

    - name: "Windows"
      os: "windows"
      python:
        - "3.7"

      services:
        - xvfb

      install: 
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install libx11-dev mesa-common-dev libglu1-mesa-dev

        - python3 -m pip install licant wheel requests psutil
        - python3 -m pip install evalcache numpy pillow pyopengl PyQt5 psutil
        - python3 -m pip install scikit-image zenframe
        
        - python3 ./setup.py install
        - python3 -m zencad --install-pythonocc-force
        - python3 -m zencad --install-occt-to-pythonocc-dir

      script:
        - cd utest
        - python3 ./api.py
        - python3 ./examples.py

     # Self Making with Display (Bionic)    PyPi
    - name: "Ubuntu: Loading from pypi"
      if: branch = master
      os: linux
      dist: bionic
      python:
        - "3.7"
            
      services:
        - xvfb

      install: 
        - python3 -m pip install zencad

      script:
        - cd utest
        - python3 ./api.py
        - python3 ./examples.py

    - name: "OSX: Loading from pypi"
      if: branch = master
      os: osx
      osx_image: xcode11.2
      language: shell
            
      install: 
        - python3 -m pip install zencad

      script:
        - cd utest
        - python3 ./api.py
        - python3 ./examples.py
