language: python

matrix:
  include:
    #- os: linux
    #  python:
    #    "3.7"
            
    #  install: 
    #    - python3 -m pip install zencad

    #  script:
    #    - cd utest
    #    - python3 ./api.py

    # Self Making without Display
    - os: linux
      python:
        "3.7"
            
      install: 
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo add-apt-repository ppa:freecad-maintainers/occt-releases -y
        - sudo add-apt-repository ppa:freecad-maintainers/freecad-stable -y
        - sudo apt-get update
        - sudo apt install -y libocct-foundation-7.3 libocct-ocaf-7.3 libocct-data-exchange-7.3 libocct-foundation-dev libocct-ocaf-dev libocct-data-exchange-dev
        - sudo apt install -y python3-pybind11

        - python3 -m pip install licant
        - python3 -m pip install evalcache numpy pillow pyopengl PyQt5 psutil
        - python3 -m pip install setproctitle
        - python3 -m pip install scikit-image

        - git clone https://github.com/mirmik/servoce --recursive
        - cd servoce 
        - python3 ./setup.py install
        - cd ..

        #- python3 -m pip install zencad
        - python3 ./setup.py install

      script:
        - cd utest
        - python3 ./api.py
        - python3 ./examples.py

    # Self Making with Display (Trusty)
    - os: linux
      dist: trusty
      python:
        "3.7"
            
      services:
        - xvfb

      install: 
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo add-apt-repository ppa:freecad-maintainers/occt-releases -y
        - sudo add-apt-repository ppa:freecad-maintainers/freecad-stable -y
        - sudo apt-get update
        - sudo apt install -y libocct-foundation-7.3 libocct-ocaf-7.3 libocct-data-exchange-7.3 libocct-foundation-dev libocct-ocaf-dev libocct-data-exchange-dev
        - sudo apt install -y python3-pybind11

        - python3 -m pip install licant
        - python3 -m pip install evalcache numpy pillow pyopengl PyQt5 psutil
        - python3 -m pip install setproctitle
        - python3 -m pip install scikit-image

        - git clone https://github.com/mirmik/servoce --recursive
        - cd servoce 
        - python3 ./setup.py install
        - cd ..

        #- python3 -m pip install zencad
        - python3 ./setup.py install

      #before_script:
        #- "export DISPLAY=:99.0"
        #- "sh -e /etc/init.d/xvfb start"
        #- sleep 3 # give xvfb some time to start

      script:
        - cd utest
        - python3 ./api.py
        - python3 ./examples.py

    # Self Making with Display (Xenial)
    - os: linux
      dist: xenial
      python:
        "3.7"
            
      services:
        - xvfb

      install: 
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo add-apt-repository ppa:freecad-maintainers/occt-releases -y
        - sudo add-apt-repository ppa:freecad-maintainers/freecad-stable -y
        - sudo apt-get update
        - sudo apt install -y libocct-foundation-7.3 libocct-ocaf-7.3 libocct-data-exchange-7.3 libocct-foundation-dev libocct-ocaf-dev libocct-data-exchange-dev
        - sudo apt install -y python3-pybind11

        - python3 -m pip install licant
        - python3 -m pip install evalcache numpy pillow pyopengl PyQt5 psutil
        - python3 -m pip install setproctitle
        - python3 -m pip install scikit-image

        - git clone https://github.com/mirmik/servoce --recursive
        - cd servoce 
        - python3 ./setup.py install
        - cd ..

        #- python3 -m pip install zencad
        - python3 ./setup.py install

      #before_script:
        #- "export DISPLAY=:99.0"
        #- "sh -e /etc/init.d/xvfb start"
        #- sleep 3 # give xvfb some time to start

      script:
        - cd utest
        - python3 ./api.py
        - python3 ./examples.py

    # Self Making with Display (Bionic)
    - os: linux
      dist: bionic
      python:
        "3.7"
            
      services:
        - xvfb

      install: 
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo add-apt-repository ppa:freecad-maintainers/occt-releases -y
        - sudo add-apt-repository ppa:freecad-maintainers/freecad-stable -y
        - sudo apt-get update
        - sudo apt install -y libocct-foundation-7.3 libocct-ocaf-7.3 libocct-data-exchange-7.3 libocct-foundation-dev libocct-ocaf-dev libocct-data-exchange-dev
        - sudo apt install -y python3-pybind11

        - python3 -m pip install licant
        - python3 -m pip install evalcache numpy pillow pyopengl PyQt5 psutil
        - python3 -m pip install setproctitle
        - python3 -m pip install scikit-image

        - git clone https://github.com/mirmik/servoce --recursive
        - cd servoce 
        - python3 ./setup.py install
        - cd ..

        #- python3 -m pip install zencad
        - python3 ./setup.py install

      #before_script:
        #- "export DISPLAY=:99.0"
        #- "sh -e /etc/init.d/xvfb start"
        #- sleep 3 # give xvfb some time to start

      script:
        - cd utest
        - python3 ./api.py
        - python3 ./examples.py

    